### ISSUE TITLE
possible problem with strategies

### ISSUE THREAD

**Issue by barisusakli** [julianlam/nodebb-plugin-sso-twitter#14]
https://github.com/julianlam/nodebb-plugin-sso-twitter/blob/master/library.js#L37

If there is an error or if the twitter key/secret is not setup then other plugins wont be able to add their strategies since the callback is never called.

**Comment by julianlam** [comment]
Thanks, legitimate issue.

**Comment by julianlam** [comment]
ca4f9f9
