### ISSUE TITLE
Unable to activate plugin

### ISSUE THREAD

**Issue by venil7** [julianlam/nodebb-plugin-sso-twitter#27]
I have installed and activated the plug in, restarted forum (many times), and even rebuilt.

But this has no effect , plugin doesnt show in admin drop down for plufins, cant be configured, and no twitter signup icon appears

**Comment by julianlam** [comment]
There should be a new admin dropdown called social authentication, it won't be added to the plugins dropdown

**Comment by venil7** [comment]
Apologies, I was probably blind.

Issue resolved
