### ISSUE TITLE
Twitter SSO fails immediately

### ISSUE THREAD

**Issue by venil7** [julianlam/nodebb-plugin-sso-twitter#28]
with the following message

```
Internal Error.
Oops! Looks like something went wrong!

/auth/twitter

Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings
```

**Comment by julianlam** [comment]
What is your callback URL?

**Comment by wellenreiter01** [comment]
I get the same error.

My callback url in the twitter app settings are:

http://forum.feathercoin.com/auth/twitter/callback
https://forum.feathercoin.com/auth/twitter/callback 

I have configured two in Twitter app

**Comment by wellenreiter01** [comment]
this seems to be a duplicate to #17 
I fixed this by configuring the app in twitter with read/write permissions and re-create the credentials in twitter.
It seems , that the sso requests full RW access to twitter. It should request the 'loing only' permission unless automatic tweets are enabled in nodebb
