### ISSUE TITLE
Twitter OAuth changes

### ISSUE THREAD

**Issue by pauljherring** [julianlam/nodebb-plugin-sso-twitter#29]
Re-opening here from https://github.com/NodeBB/NodeBB/issues/6719

> `/admin/plugins/sso-twitter` links to a deprecated (as of July '18) URL: https://apps.twitter.com/
>
>> As of July 2018, you must [apply for a Twitter developer account](https://developer.twitter.com/en/apply/user) and be approved before you may create new apps. Once approved, you will be able to create new apps from developer.twitter.com.
>>
>> For the near future, you can continue to manage existing apps here on apps.twitter.com. However, we will soon retire this site and consolidate all developer tools, API access, and app management within the developer portal at developer.twitter.com. You will be able to access and manage existing apps through that portal when we retire this site.

**Comment by julianlam** [comment]
I'm assuming the backend functionality of this plugin is not impacted? If so, then the only change is really just the blurb on the admin page...

**Comment by pauljherring** [comment]
I believe it's only the boilerplate, yes. But I'm having problems sorting out our instance - the tardiness of twitter activating a new dev account being the primary one at the moment, rather than anything in the plugin.

Background here:

https://what.thedailywtf.com/topic/25615/twitter-oauth-problem/11
