### ISSUE TITLE
Don't Work 

### ISSUE THREAD

**Issue by Master-Antonio** [julianlam/nodebb-plugin-sso-twitter#8]
I have the 0.4.0 .
But don't work.
I put Api Key and Secret but don't save.

**Comment by TedRinehart** [comment]
Working fine on 0.6.0. :+1:

**Comment by fczuardi** [comment]
@Master-Antonio mine worked after I added  http://myforumurl**/auth/twitter/callback** as the callback url on the twitter app page **and** edited my config.json file to use the url instead of localhost:4567
